config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :models
  devise_for :user
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
validates_uniqueness_of :name
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

validates_presence_of :description
validates_presence_of :price
validates_presence_of :title
validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0, :less_than => 10} 

def average_rating
  reviews = self.reviews
  review_sum = reviews.inject(0) { |sum, review| sum += review.rating }
  avg_rating = review_sum.fdiv(reviews.count)
end




end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

validates_presence_of :content 
validates_presence_of :rating 
validates_presence_of :user_id 

def self.funkcja(item)
client=Review.where(user_id: item).last(5)
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :products

validates_presence_of :lastname
validates_presence_of :firstname



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception


  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation) }

        end






end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
if current_user.admin?	

else
redirect_to new_user_session_url

end

  end

  def edit
if current_user.admin?	

else
redirect_to new_user_session_url

end
  end

  def create
if current_user.admin?	
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
else
redirect_to new_user_session_url

end
  end

  def update
if current_user.admin?	
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
else
redirect_to new_user_session_url

end

  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :author!, only: [:edit, :update]
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

def author!
  unless self.product.user == current_user
    redirect_to category_product_url(category, product),
      flash: { error: 'You are not allowed to edit this product.' }
  end
end

  def index
  end

  def show
  end

  def new
  end

  def edit

  end

  def create
if user_signed_in?	



    self.product = Product.new(product_params)
    self.product.user_id = current_user.id
    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
else
redirect_to new_user_session_url

end

  end

  def update
if user_signed_in?	



    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end




else
redirect_to new_user_session_url

end
  end

  # DELETE /products/1
  def destroy
if user_signed_in?
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'

else
redirect_to new_user_session_url

end

  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)


  def edit
  end

  def create
    self.review = Review.new(review_params)
    self.review.user_id = current_user.id
    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end



  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
  @user = User.find(current_user.id)
  @nowa = Review.funkcja(current_user.id)

end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'
%br
= link_to 'Show', category, class: 'btn btn-success'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Listing categories

%table.table
  %tr
    %th Name
    %th
    %th
    %th

  - categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Show', category, class: 'btn btn-sm btn-success'
      -if current_user.try(:admin?)
        %td= link_to 'Edit', edit_category_path(category), class: 'btn btn-sm btn-warning'
      -if current_user.try(:admin?)
        %td= link_to 'Destroy', category, class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' }

%br
-if current_user.try(:admin?)
  = link_to 'New Category', new_category_path, class: 'btn btn-primary'

app/views/categories/new.html.haml
%h1 New category

= render 'form'
%br
= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html (kopia).haml
%p#notice= notice

%p
  %b Name:
  = category.name

%table.table


  - category.products.each do |product|
    %tr
      %td= product.title
      %td= link_to 'Show', category_product_path(product.category_id, product), class: 'btn btn-sm btn-success'
      -if current_user.try(:admin?)      
        %td= link_to 'Edit', edit_category_product_path(product.category_id, product), class: 'btn btn-sm btn-warning'
      -if current_user.try(:admin?)
        %td= link_to 'Destroy', category_product_path(product.category_id, product), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' }
     
%br
  %h3 New product
  = render 'products/form'

= link_to 'Edit', edit_category_path(category), class: 'btn btn-success'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Category:
  = category.name

%table.table


  - category.products.each do |product|
    %tr
      %td= product.title
      %td= link_to 'Show', category_product_path(product.category_id, product), class: 'btn btn-sm btn-success'
      -if current_user.try(:admin?)      
        %td= link_to 'Edit', edit_category_product_path(product.category_id, product), class: 'btn btn-sm btn-warning'
      -if current_user.try(:admin?)
        %td= link_to 'Destroy', category_product_path(product.category_id, product), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' }
     
%br
  %h3 New product
  = render 'products/form'

= link_to 'Edit', edit_category_path(category), class: 'btn btn-success'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %span.navbar-brand #{AppConfig.workshops_name}
        %p.navbar-text.navbar-right
          = link_to('Category list', root_path, class: 'btn btn-success')
          -if user_signed_in?
            = link_to('User profile', users_index_path, class: 'btn btn-primary')
            = link_to('Logout', destroy_user_session_path,  :method=>'delete', class: 'btn btn-primary')
          -else
            = link_to('Login', new_user_session_path, class: 'btn btn-primary')
            = link_to('Sign up ', new_user_registration_path, class: 'btn btn-primary')
    .container-fluid
      .row
        .col-lg-6
          .jumbotron
            %H1 Neguru Szczecin Workshops 2015     
            %H3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas egestas molestie nibh vitae posuere. Donec magna dolor, viverra non commodo et, facilisis a nulla. Praesent aliquet, massa eget hendrerit sodales, velit justo suscipit nibh, porttitor pellentesque nisl elit ut sem. Morbi eu elementum sapien. Phasellus at commodo nibh, ut vestibulum nibh. Curabitur commodo, nibh at vulputate tristique, dolor arcu efficitur odio, in dapibus orci elit sed lacus. Donec et nisl tristique.
        .col-lg-6   
          = yield

app/views/products/index.html.haml
%h1 Listing products

%table.table
  %tr
    %th Title
    %th Description
    %th Price
    %th
    %th
    %th

  - products.each do |product|
    %tr
      %td= product.title
      %td= product.description
      %td= product.price
      %td= link_to 'Show', category_product_path(product.category_id, product)
      %td= link_to 'Edit', edit_category_product_path(product.category_id, product)
      %td= link_to 'Destroy', category_product_path(product.category_id, product), method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/products/show.html.haml
%p#notice= notice
%p#error= flash[:error]

%p
  %b Title:
  = product.title
%p
  %b Description:
  = product.description
%p
  %b Price:
  = product.price

%p
  %b Category
  = product.category.name

%h3 Reviews
= render 'reviews/form'

= render reviews
%br
= link_to 'Edit', edit_category_product_path(category.id, product.id), class: 'btn btn-success'

= link_to 'Back', category_products_path, class: 'btn btn-primary'

app/views/reviews/_review.html.haml
%br
%div.panel.panel-default
  .panel-body
    %p= review.content
  .panel-footer
    Rating: 
    %b= review.rating
    .text-right
      Author:
      %em= review.author 

app/views/reviews/new.html .haml
%p= review.content
%p
  %b= review.rating
  %em= review.author

app/views/users/index.html.haml
%h1 Profil użytkownika:
%h2= "#{ @user.firstname } #{ @user.lastname }"
%h3= @user.email
%br
%h3 Ostatnie wpisy użytkownika:

%table.table
  %tr
    %th Treść
    %th Ocena
    %th Data

  - @nowa.each do |nowa|
    %tr
      %td= nowa.content
      %td= nowa.rating
      %td= nowa.created_at.strftime("%m-%d-%Y")

      